name: Deploy My React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '9.8.0' 

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t jntcruz/crm-react .

      - name: Push Docker image
        run: docker push jntcruz/crm-react